/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/abandoned-warehouse-interior-scene-1d5285f2e0fd4211a27c8042496d5959
title: Abandoned Warehouse - Interior Scene
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spaceman({ ...props }) {
    const spaceman = useRef()
    // Auto-generated by: https://github.com/pmndrs/gltfjsx
    const Spaceman = forwardRef(({ children, ...props }, ref) => {
        const { nodes, materials } = useGLTF('/Astronaut-transformed.glb')
        return (
            <mesh
                castShadow
                receiveShadow
                ref={ref}
                {...props}
                geometry={nodes.Astronaut_mesh.geometry}
                material={materials.Astronaut_mat}
                material-envMapIntensity={0}
                dispose={null}>
                {children}
            </mesh>
        )
    });

    Spaceman.displayName = 'Spaceman';
    return (
        <Spaceman {...props} >
            <object3D ref={spaceman} />
        </Spaceman>
    )
}
