/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Cem Gürbüz (https://sketchfab.com/cemgurbuzz)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/ant-miner-s19-pro-4fb91310fa474cfa907d4100ee634050
title: Ant Miner S19 Pro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function AsicMiner({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ant_miner_s19_pro/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 108.07, 0]} scale={0.49}>
            <mesh geometry={nodes.Antminer_2_Base_Antminer_Metal_0.geometry} material={materials.Antminer_Metal} />
            <mesh geometry={nodes.Antminer_2_Base_Dark_0.geometry} material={materials.Dark} />
            <mesh geometry={nodes.Antminer_2_Base_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[223.17, 61.24, -154.56]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.79, 0.78, 0.78]}>
            <mesh geometry={nodes.Warning_Sign_2_Warning_Sign_0.geometry} material={materials.Warning_Sign} />
          </group>
          <group position={[0.06, 108.1, 259.31]} rotation={[Math.PI / 2, 0, 0]} scale={1.01}>
            <mesh geometry={nodes.Fan_Base_2_Black_Fan_0.geometry} material={materials.Black_Fan} />
            <mesh geometry={nodes.Fan_Base_2_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[0.2, 106.01, 260.51]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.39}>
            <mesh geometry={nodes.Fan_2_2_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[0.2, 320.75, 260.51]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.39}>
            <mesh geometry={nodes.Fan_2_1_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[165.24, 197.4, -144.39]} scale={0.49}>
            <mesh geometry={nodes.Antminer_2_R_Dark_0.geometry} material={materials.Dark} />
            <mesh geometry={nodes.Antminer_2_R_Antminer_Metal_0.geometry} material={materials.Antminer_Metal} />
            <mesh geometry={nodes.Antminer_2_R_Metal_0.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Antminer_2_R_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[0, 108.97, 0]} scale={0.49}>
            <mesh geometry={nodes.Antminer_2_U_Dark_0.geometry} material={materials.Dark} />
            <mesh geometry={nodes.Antminer_2_U_Antminer_Metal_0.geometry} material={materials.Antminer_Metal} />
            <mesh geometry={nodes.Antminer_2_U_Lights_0.geometry} material={materials.Lights} />
            <mesh geometry={nodes.Antminer_2_U_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[0.48, 108.97, 0]} scale={0.49}>
            <mesh geometry={nodes.Antminer_2_R_U_Antminer_Metal_0.geometry} material={materials.Antminer_Metal} />
          </group>
          <group position={[163.79, 369.83, 144.15]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.2}>
            <mesh geometry={nodes.Fan_2_R_1_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[163.79, 260.51, 144.15]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.2}>
            <mesh geometry={nodes.Fan_2_R_2_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[163.79, 151.19, 144.15]} rotation={[Math.PI / 2, 0.05, 0]} scale={0.2}>
            <mesh geometry={nodes.Fan_2_R_3_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[163.77, 260.24, 155.09]} rotation={[Math.PI / 2, 0, 0]} scale={0.51}>
            <mesh geometry={nodes.Fan_Base_2_R_Black_Fan_0.geometry} material={materials.Black_Fan} />
            <mesh geometry={nodes.Fan_Base_2_R_Metal_0.geometry} material={materials.Metal} />
          </group>
          <group position={[109.58, 439.39, 211.11]} rotation={[1.43, -0.14, -0.02]} scale={0.49}>
            <mesh geometry={nodes.Cable_2_1_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
          <group position={[-108.8, 439.39, -269.2]} rotation={[1.72, 0.14, 3.12]} scale={0.49}>
            <mesh geometry={nodes.Cable_2_2_Black_Fan_0.geometry} material={materials.Black_Fan} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
