/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/abandoned-warehouse-interior-scene-1d5285f2e0fd4211a27c8042496d5959
title: Abandoned Warehouse - Interior Scene
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Ship({ ...props }) {
    const ship = useRef()
    // One-click copy/paste from the poimandres market: https://market.pmnd.rs/model/low-poly-spaceship
    const Ship = forwardRef((props, ref) => {
        const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/low-poly-spaceship/model.gltf')
        return (
            <group ref={ref} {...props} dispose={null}>
                <mesh castShadow receiveShadow geometry={nodes.Cube005.geometry} material={materials.Mat0} />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_1.geometry} material={materials.Mat1} material-color="black" />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_2.geometry} material={materials.Mat2} material-envMapIntensity={0.2} material-color="black" />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_3.geometry} material={materials.Window_Frame} />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_4.geometry} material={materials.Mat4} />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_5.geometry} material={materials.Mat3} />
                <mesh castShadow receiveShadow geometry={nodes.Cube005_6.geometry} material={materials.Window} />
            </group>
        )
    })

    Ship.displayName = 'Ship';
    return (
        <Ship ref={ship} {...props} />
    )
}
