/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/abandoned-warehouse-interior-scene-1d5285f2e0fd4211a27c8042496d5959
title: Abandoned Warehouse - Interior Scene
*/

import React, { forwardRef, useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spaceman({ ...props }) {

    const coords = useRef(props.position)
    // [10, 3, -0.5]
    // const [coords, setCoords] = useState({ x : props.position[0], y : props.position[1], z : props.position[2] });

    const spaceman = useRef()
    // Auto-generated by: https://github.com/pmndrs/gltfjsx
    const Spaceman = forwardRef(({ children, ...props }, ref) => {
        const { nodes, materials } = useGLTF('/Astronaut-transformed.glb')
        return (
            <mesh
                castShadow
                receiveShadow
                ref={ref}
                {...props}
                geometry={nodes.Astronaut_mesh.geometry}
                material={materials.Astronaut_mat}
                material-envMapIntensity={0}
                dispose={null}>
                {children}
            </mesh>
        )
    });

    Spaceman.displayName = 'Spaceman';
    // movement - please calibrate these values
    const xSpeed = 0.1;
    const ySpeed = 0.1;

    useEffect(() => {
        function onDocumentKeyDown(event) {
            let currectCoords = { x : coords[0], y : coords[1], z : coords[2] };

            var keyCode = event.which;
            if (keyCode == 87 || keyCode == 38) {
                currectCoords.y += ySpeed;
            } else if (keyCode == 83 || keyCode == 40) {
                currectCoords.y -= ySpeed;
            } else if (keyCode == 65 || keyCode == 37) {
                currectCoords.x -= xSpeed;
            } else if (keyCode == 68 || keyCode == 39) {
                currectCoords.x += xSpeed;
            } else if (keyCode == 32) {
                currectCoords = { x: 10, y: 3, z: -0.5 }; // { x : 0, y : 0, z : 0 };
            }
            
            props.position = [currectCoords.x, currectCoords.y, currectCoords.z]
            console.log(currectCoords);
            console.log(keyCode)
        };

        document.addEventListener("keydown", onDocumentKeyDown, false);

        return (
            <Spaceman {...props}>
                <object3D ref={spaceman} />
            </Spaceman>
        )
    });



    return (
        <Spaceman {...props}>
            <object3D ref={spaceman} />
        </Spaceman>
    )
}
