/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aurélien Martel (https://sketchfab.com/aurelien_martel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/abandoned-warehouse-interior-scene-1d5285f2e0fd4211a27c8042496d5959
title: Abandoned Warehouse - Interior Scene
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Spaceman({ ...props }) {
    const spaceman = useRef()
    // Auto-generated by: https://github.com/pmndrs/gltfjsx
    const Spaceman = forwardRef(({ children, ...props }, ref) => {
        const { nodes, materials } = useGLTF('/Astronaut-transformed.glb')
        return (
            <mesh
                castShadow
                receiveShadow
                ref={ref}
                {...props}
                geometry={nodes.Astronaut_mesh.geometry}
                material={materials.Astronaut_mat}
                material-envMapIntensity={0}
                dispose={null}>
                {children}
            </mesh>
        )
    });

    Spaceman.displayName = 'Spaceman';

    function onDocumentKeyDown(event) {
        let currectCoords = coords;
    
        var keyCode = event.which;
        if (keyCode == 87 || keyCode == 38) {
            currectCoords.y += ySpeed;
        } else if (keyCode == 83 || keyCode == 40) {
            currectCoords.y -= ySpeed;
        } else if (keyCode == 65 || keyCode == 37) {
            currectCoords.x -= xSpeed;
        } else if (keyCode == 68 || keyCode == 39) {
            currectCoords.x += xSpeed;
        } else if (keyCode == 32) {
            currectCoords ={ x : 10, y : 3, z : -0.5 }; // { x : 0, y : 0, z : 0 };
        }
    
        setCoords(currectCoords);
        console.log(currectCoords);
        console.log(keyCode)
    };
    
    return (
        <Spaceman {...props} >
            <object3D ref={spaceman} />
        </Spaceman>
    )
}
